server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gurzsky/ead-config-server-repo
          default-label: main
          username: gurzsky
          password: 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

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost