server:
  port: ${PORT}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gurzsky/ead-config-server-repo
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

encrypt:
  key: dSgVkYp2s5v8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x!A%D*G-

ead:
  configServer:
    username: ${CONFIG_SERVER_USERNAME}
    password: ${CONFIG_SERVER_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80